//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiServices.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public partial class tblEmployee
    {
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public Nullable<double> Salary { get; set; }
        [DataMember]
        public string Gender { get; set; }
        [DataMember]
        public Nullable<int> Departmentid { get; set; }
    
        public virtual tblDepartment tblDepartment { get; set; }
    }
}
